### ISSUE TITLE
USB Passthrough ? (Iphone not detected)

### ISSUE THREAD

**Issue by AurelienKun** [hackintosh-guides/macOS-VMware-Guide#1]
First, you really deserve an high five for this amazing guide !
So here is my problem:
Actually I'd like to connect an iphone to the VM in order to play around with XCode. But even if I set a rule in VMWare to connect it to the VM, not the host, the system does not recognize anything, and nothing happens to the phone itself. It make just the usual sound when it is plugged to a powersource.
If you have any solution to achieve this, it would be amazing if you could update your guide.
Thank you !

**Comment by CDeLeon94** [comment]
Did you find a solution to this?
