### ISSUE TITLE
Cannot run after changing ethernet address

### ISSUE THREAD

**Issue by ghost** [hackintosh-guides/macOS-VMware-Guide#5]
I can not start the VM after changing the MAC address. I get the following error.
```
Error while powering on: Specify a static Ethernet address for 'ethernet0'.

Could not set up 'macAddress' for 'ethernet0'.

Module 'DevicePowerOn' power on failed.

Failed to start the virtual machine.
```
I am unsure how to fix this, I have tried multiple different MAC addresses from the site but have not had any luck.

**Comment by AlexTheGreat4000** [comment]
Could you upload screenshots of those lines you edited from your .vmx file

**Comment by ghost** [comment]
> 
> 
> Could you upload screenshots of those lines you edited from your .vmx file

![1](https://user-images.githubusercontent.com/47761974/108007259-8415d680-6fcb-11eb-836a-69a38f05d3bb.png)
![2](https://user-images.githubusercontent.com/47761974/108007260-84ae6d00-6fcb-11eb-8b8a-b554458a0454.png)

**Comment by AlexTheGreat4000** [comment]
You need to change "ethernet0.generatedAddress" to "ethernet0.Address". You also need to change "ethernet0.generatedAddressOffset" to "ethernet0.checkMACAddress"

**Comment by ghost** [comment]
> 
> 
> You need to change "ethernet0.generatedAddress" to "ethernet0.Address". You also need to change "ethernet0.generatedAddressOffset" to "ethernet0.checkMACAddress"

Now I get the following error once booting the machine.
![error](https://user-images.githubusercontent.com/47761974/108008580-ad843180-6fce-11eb-9f80-9c16743c5fbb.png)

**Comment by AlexTheGreat4000** [comment]
Boot to the macOS installer and run this command in Terminal `nvram boot-args="-v"`

**Comment by ghost** [comment]
> 
> 
> Boot to the macOS installer and run this command in Terminal `nvram boot-args="-v"`

I am getting the same error. I am now redownloading the disk file and will try from there.

**Comment by ghost** [comment]
> 
> 
> > Boot to the macOS installer and run this command in Terminal `nvram boot-args="-v"`
> 
> I am getting the same error. I am now redownloading the disk file and will try from there.

I got the same error again with a fresh vmdk file.

**Comment by AlexTheGreat4000** [comment]
Same error as: https://user-images.githubusercontent.com/47761974/108008580-ad843180-6fce-11eb-9f80-9c16743c5fbb.png
or a different error? 
If it's different, upload a photo

**Comment by ghost** [comment]
> 
> 
> Same error as: https://user-images.githubusercontent.com/47761974/108008580-ad843180-6fce-11eb-9f80-9c16743c5fbb.png
> or a different error?
> If it's different, upload a photo

Same error, I was able to revert the vmx file and login and ran the command and generated new values in the Clover Configurator, I have updated the file and have the same problem. At first it appears it will boot and then it reverts back to the vmware bootup screen and then I get the same error.
![error](https://user-images.githubusercontent.com/47761974/108014948-14104c00-6fdd-11eb-8194-ebaf0df314fb.png)

**Comment by ghost** [comment]
Also, in case it matters as I cannot use VirtualBox due to it I have Hyper-V enabled.

**Comment by ghost** [comment]
I appear to have fixed this by disabling Hyper-V.

**Comment by AlexTheGreat4000** [comment]
Was just about to write the same thing. I will mark this issue as closed

**Comment by tylerwolf35** [comment]
> 
> 
> Was just about to write the same thing. I will mark this issue as closed

hey, im now getting the following error. I have previously gotten stuck at EXITBS:START on other VMs due to being on an AMD CPU, but this guide is geared towards AMD. Is this a known issue and is there a way to fix this?
![error1](https://user-images.githubusercontent.com/47761974/108125664-c811e580-7076-11eb-9ad3-9dbed892058e.png)
